# include configuration file
include:
    "../../rules/ini/config"

# define the data types used
TYPES = ['mg', 'mt']
# type pf the merged assembly
ASS = 'mgmt'

#include:
#    "../../rules/databases.rules"

workdir:
    OUTPUTDIR

# include rules for the workflow
include:
    "Preprocessing"

include:
    "Assembly"

include:
    "Analysis"

include:
    "Report"

# master command
rule ALL:
    input:
        "preprocessing.done",
        "assembly.done",
        "analysis.done",
        "report.done"
    output:
        touch('workflow.done')
