#!/usr/bin/env python3
from lib.docopt import docopt
from lib.path import Path
import subprocess
import os
import json
import shlex

__doc__ = """Integrated Metaomic Pipeline.
 ____  __  __  ____
(_  _)(  \/  )(  _ \\
 _)(_  )    (  )___/
(____)(_/\/\_)(__)

Usage:
  IMP -d DATA -o OUTPUT [--enter] [-n CONTAINER] [-e ENV] ... [COMMANDS ...]
  IMP (-h | --help)
  IMP --version

Options:
  -d DATA             Path to the data
  -e ENV              Environment variable to pass to the container
  --enter             Enter the container
  -h --help           Show this help and exit
  -n CONTAINER        Name of the container. Useful when you want to run a previous version of IMP.
  -o OUTPUT           Path to the output directory

"""


def get_version():
    return subprocess.check_output(
        ['git', '--no-pager', 'log', '-n', '1', '--pretty=format:%H']
    )

if __name__ == '__main__':
    args = docopt(__doc__, version=get_version(), options_first=True)

    CURRENT_PATH = Path(__file__).parent.abspath()
    print(args)

    data = Path(args['-d']).abspath()
    output = Path(args['-o']).abspath()
    container_name = args['-n'] is not None and args['-n'] or 'imp:latest'

    # configure IMP mount point to the docker container
    mount_points = [
        '-v %s:/data' % data,
        '-v %s:/home/imp/integrated-metaomic-pipeline' % CURRENT_PATH,
        '-v %s:/output' % output
    ]
    # environement variables
    envs = ['-e {}="{}"'.format(*e.split('=')) for e in args['-e']]

    # CL
    cmd = ['docker', 'run'] + mount_points + envs
    # reconfigure entrypoint if --enter flag is specified
    if args['--enter']:
        cmd += ['--entrypoint /bin/bash -it']
    # add container name and commands to pass to snakemake
    cmd += [container_name] + args['COMMANDS']
    # parse CL correctly
    cmd = shlex.split(' '.join(cmd))
    print("Executing", '"', ' '.join(cmd), '"')
    subprocess.call(cmd)
