# Base container with tools dependencies for the IMP pipeline
#
# VERSION       1.4.1

FROM ubuntu:trusty
MAINTAINER yohan.jarosz@uni.lu

################
# dependencies #
################
RUN echo "deb ftp://ftp.halifax.rwth-aachen.de/ubuntu trusty main restricted universe multiverse" > /etc/apt/sources.list \
    && echo "deb ftp://ftp.halifax.rwth-aachen.de/ubuntu trusty-security main restricted universe" >> /etc/apt/sources.list \
    && echo "deb ftp://ftp.halifax.rwth-aachen.de/ubuntu trusty-updates main restricted universe multiverse">> /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -yq python-software-properties software-properties-common \
    && add-apt-repository "deb http://cran.stat.ucla.edu/bin/linux/ubuntu trusty/" \
    && gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9 \
   # && apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv-keys E084DAB9 \
    && gpg -a --export E084DAB9 | apt-key add - \
    && apt-get update \
    && apt-get -yq upgrade \
    && rm -rf /var/lib/apt/lists/*

RUN  apt-get update \
    && apt-get install -yq make cmake wget build-essential unzip ant git tig vim \
    && rm -rf /var/lib/apt/lists/*

RUN  apt-get update \
    && apt-get install -yq openjdk-7-jdk \
    && rm -rf /var/lib/apt/lists/*

#bioperl needs to be 1.6.924 for amphora2 # not available through apt-get for trusty...
RUN (echo y;echo o conf prerequisites_policy follow;echo o conf commit)|cpan -e force install CJFIELDS/BioPerl-1.6.924.tar.gz
    #&& apt-get install -yq bioperl=1.6.923-1 \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get install -yq tabix=0.2.6-2 zlib1g zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get install -yq samtools gnuplot python3 \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get install -yq python-numpy python-scipy python-matplotlib python-sklearn \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get install -yq r-base r-base-dev \
    && apt-get install -yq libncurses5 libncurses5-dev sudo libatlas-base-dev python2.7 gfortran python-dev \
    && apt-get install -yq python-matplotlib \
    && update-alternatives --set java /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java \
    && rm -rf /var/lib/apt/lists/*

## Python dependencies and bioservices. Using version 1.3.5 because script doesn't work with latest version
RUN mkdir -p /home/imp/tmp /home/imp/lib \
    && cd /home/imp/tmp \
    && wget https://bootstrap.pypa.io/get-pip.py \
    && python3 get-pip.py \
    && python2.7 get-pip.py \
    && pip3 install snakemake docopt \
    && pip2.7 install numpy \
    && pip2.7 install scipy scikit-learn docopt \
    && pip install -Iv https://pypi.python.org/packages/source/b/bioservices/bioservices-1.3.5.tar.gz \
    && rm get-pip.py
