# Base container with tools needed for the IMP pipeline
#
# VERSION       1.4.1

FROM docker-r3lab.uni.lu/imp/imp:1.3
MAINTAINER yohan.jarosz@uni.lu

######################################
#        Tools installations         #
######################################

## Reinstall bioperl
RUN (echo y;echo o conf prerequisites_policy follow;echo o conf commit)|cpan -f -i CJFIELDS/BioPerl-1.6.924.tar.gz \
    #&& apt-get install -yq bioperl=1.6.923-1 \
    && rm -rf /var/lib/apt/lists/*

## CheckM
RUN cd /home/imp/lib \
    && pip2.7 install pysam dendropy ScreamingBackpack \
    && wget https://github.com/Ecogenomics/CheckM/archive/v1.0.6.tar.gz \
    && tar xf v1.0.6.tar.gz \
    && cd CheckM-1.0.6/ \
    && python2.7 setup.py install \
    && cd .. \
    && rm -r CheckM-1.0.6/ \
    && wget https://github.com/matsen/pplacer/releases/download/v1.1.alpha17/pplacer-Linux-v1.1.alpha17.zip \
    && unzip pplacer-Linux-v1.1.alpha17.zip \
    && cp pplacer-Linux-v1.1.alpha17/guppy /usr/bin \
    && cp pplacer-Linux-v1.1.alpha17/pplacer /usr/bin \
    && rm -r pplacer-Linux-v1.1.alpha17

##CheckM Data
RUN cd /home/imp/lib \
    && wget https://data.ace.uq.edu.au/public/CheckM_databases/checkm_data_v1.0.6.tar.gz

RUN cd /home/imp/lib \
    && mkdir checkm_data_v1.0.6 \
    && tar -xf checkm_data_v1.0.6.tar.gz -C checkm_data_v1.0.6 \
    #echo used for interactive prompt
    && echo checkm_data_v1.0.6 | checkm data setRoot checkm_data_v1.0.6/


##Amphora2
RUN cd /home/imp/lib \
    && git clone https://github.com/mherold1/AMPHORA2 \
    && wget https://github.com/stamatak/standard-RAxML/archive/v8.2.8.tar.gz -O stamatak-standard-RAxML.tar.gz \
    && tar xf stamatak-standard-RAxML.tar.gz \
    && cd standard-RAxML-8.2.8; make -f Makefile.gcc; make -f Makefile.PTHREADS.gcc; sudo cp raxmlHPC* /usr/bin/. \
    && cd .. \
    && (echo y;echo o conf prerequisites_policy follow;echo o conf commit)|cpan -f -i Parallel::ForkManager
#    && wget ftp://emboss.open-bio.org/pub/EMBOSS/old/6.5.0/EMBOSS-6.5.7.tar.gz \
#    && tar -xf EMBOSS-6.5.7.tar.gz \
#    && cd EMBOSS-6.5.7 \
#    && ./configure \
#    && make \
#    && make install
#    FOR NOW: using apt-get install emboss
#    && apt-get install emboss
RUN cd /home/imp/lib \
    && sudo apt-get update \
    && echo y| sudo apt-get install emboss
   # && wget ftp://emboss.open-bio.org/pub/EMBOSS/old/6.5.0/EMBOSS-6.5.7.tar.gz \
   # && tar -xf EMBOSS-6.5.7.tar.gz \
   # && cd EMBOSS-6.5.7 \
  #  && ./configure --without-mysql --without-postgresql --without-axis2c --without-hpdf --without-x\
 #   && make \
    #&& make install \
    #&& ldconfig \
#    && make install 

##pullseq
RUN cd /home/imp/lib \
    && git clone https://github.com/bcthomas/pullseq \
    && cd pullseq \
    && ./bootstrap \
    && ./configure \
    && make \
    && make install

##Phylophlan, removed for now maybe revisit at a later timepoint, MH 16.6.2016
#RUN cd /home/imp/lib \
##    && wget https://bitbucket.org/nsegata/phylophlan/get/default.tar.gz \
##    && tar -xf default.tar.gz \
#    && pip install mercurial \
#    && hg clone https://bitbucket.org/nsegata/phylophlan \
##    && cd phylophlan \
##for development version: (stick to old one for now)
##    && hg pull && hg update dev \ 
#    && wget http://www.microbesonline.org/fasttree/FastTree \
#    && chmod +x FastTree \
#    && cp FastTree /usr/bin \
##usearch binary copied from gaia for now and put in imp code -> need to solve this 

#
#    #move usearch binary to webdav? this uses my downloadlink, from 2.5.2016 , not sure how long this works.
##    && wget --user-agent=Mozilla --content-disposition -E -c http://drive5.com/cgi-bin/upload3.py?license=2016050205235811143 \
# #   && chmod +x usearch8.1.1861_i86linux32 \
#  #  && cp usearch8.1.1861_i86linux32 /usr/bin/usearch \
##    && cd  \

# This cleans the old git repo and downloads the new one. Remember to replace with a proper 
# tag when released
RUN cd /home/imp/code \
    && rm -rf ./* \
    && rm -rf ./.git* \
    && git clone --branch binning_refactor2 --single-branch https://git-r3lab.uni.lu/IMP-dev/IMP.git .

# R with checkpoint libraries
ADD dependencies.R /home/imp/lib/
RUN mkdir -p /home/imp/lib/.checkpoint \
    && echo "r <- getOption('repos'); r['CRAN'] <- 'http://cran.us.r-project.org'; options(repos = r);" > /home/imp/.Rprofile \
    && Rscript -e "install.packages('checkpoint')" \
    && Rscript -e "library(checkpoint);checkpoint('2016-06-20', project='/home/imp/lib', checkpointLocation='/home/imp/lib')" \
    && Rscript -e "source('http://bioconductor.org/biocLite.R');biocLite('genomeIntervals')"

RUN wget https://webdav-r3lab.uni.lu/public/R3lab/IMP/linux64.tbl2asn.gz -O /tmp/tbl2asn.gz \
    && gzip -d /tmp/tbl2asn.gz \
    && chmod +x /tmp/tbl2asn \
    && sudo mv /tmp/tbl2asn /usr/bin

######################
# runtime parameters #
######################
ENV AMPHORA2_home /home/imp/lib/AMPHORA2  ###CHECK IF THIS IS CORRECT?
ENV PATH /home/imp/lib/pullseq/src:/home/imp/lib/trinityrnaseq_r20140717:/home/imp/lib/Platypus_0.8.1:/home/imp/lib/megahit:/home/imp/lib/fastqc/FastQC:$PATH
ENV LD_LIBRARY_PATH /usr/local/lib/:/home/imp/lib/Platypus_0.8.1
VOLUME ["/home/imp/data", "/home/imp/output", "/home/imp/databases", "/home/imp/code"]
WORKDIR /home/imp/code

CMD ["snakemake", "ALL"]
